=== giodabg/NetBeansProject/NB_XMLParser/NB_XMLParser/myXMLDocument.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/myXMLDocument.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE Employees SYSTEM "myXMLDocument.dtd">

    <Employees>
    ...
    </Employees>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Employees (Employee)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Employee (Firstname|Lastname|Age|Salary)*>
<!ATTLIST Employee
    ID CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Firstname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Lastname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Age (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Salary (#PCDATA)>

=== giodabg/NetBeansProject/NB_XMLParser/NB_XMLParser/myXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employees SYSTEM "myXMLDocument.dtd">

<Employees>
<Employee ID="10">
<Firstname>Lebron</Firstname >
<Lastname>James</Lastname>
<Age>30</Age>
<Salary>2500</Salary>
</Employee>
<Employee ID="20">
        <Firstname>Anthony</Firstname>
        <Lastname>Davis</Lastname>
        <Age>22</Age>
        <Salary>1500</Salary>
    </Employee>
    <Employee ID="30">
        <Firstname>Paul</Firstname>
        <Lastname>George</Lastname>
        <Age>24</Age>
        <Salary>2000</Salary>
    </Employee>
    <Employee ID="40">
        <Firstname>Blake</Firstname>
        <Lastname>Griffin</Lastname>
        <Age>25</Age>
        <Salary>2250</Salary>
    </Employee>
</Employees>
